import 'package:closho/constants/strings.dart';
import 'package:closho/model/itemModel.dart';

//kids dress
ItemModel itemModel1 = ItemModel(
    id: DateTime.now().microsecondsSinceEpoch,
    name: "Sharvani",
    amount: 1500.0,
    imagePath: [
      "${dressKids + "1.1.jpg"}",
      "${dressKids + "1.jpeg"}",
      "${dressKids + "1.2.jpg"}",
    ],
    sizeList: [true, true, false, false],
    colorList: [],
    haveOffer: true,
    offerPer: 40,
    dateTime: DateTime.now(),
    indexNo: 0,
    category: dress,
    gender: kid,
    isAsset: true);
ItemModel itemModel2 = ItemModel(
    id: DateTime.now().microsecondsSinceEpoch,
    name: "Little Top",
    amount: 700.0,
    imagePath: [
      "${dressKids + "2.1.jpg"}",
      "${dressKids + "2.jpg"}",
    ],
    sizeList: [true, true, false, false],
    colorList: [],
    haveOffer: false,
    offerPer: 40,
    dateTime: DateTime.now(),
    indexNo: 0,
    category: dress,
    gender: kid,
    isAsset: true);
ItemModel itemModel3 = ItemModel(
    id: DateTime.now().microsecondsSinceEpoch,
    name: "Umbrella Top",
    amount: 800.0,
    imagePath: [
      "${dressKids + "3.1.jpg"}",
      "${dressKids + "3.jpg"}",
      "${dressKids + "3.2.jpg"}",
    ],
    sizeList: [true, true, false, false],
    colorList: [],
    haveOffer: true,
    offerPer: 20,
    dateTime: DateTime.now(),
    indexNo: 0,
    category: dress,
    gender: kid,
    isAsset: true);
ItemModel itemModel4 = ItemModel(
    id: DateTime.now().microsecondsSinceEpoch,
    name: "Lite Stripo",
    amount: 1000.0,
    imagePath: [
      "${dressKids + "4.1.jpg"}",
      "${dressKids + "4.jpeg"}",
    ],
    sizeList: [true, true, false, false],
    colorList: [],
    haveOffer: true,
    offerPer: 50,
    dateTime: DateTime.now(),
    indexNo: 0,
    category: dress,
    gender: kid,
    isAsset: true);
ItemModel itemModel5 = ItemModel(
    id: DateTime.now().microsecondsSinceEpoch,
    name: "Half Curtha",
    amount: 1200.0,
    imagePath: [
      "${dressKids + "5.1.jpg"}",
      "${dressKids + "5.jpg"}",
      "${dressKids + "5.2.jpg"}",
    ],
    sizeList: [true, true, false, false],
    colorList: [],
    haveOffer: false,
    offerPer: 40,
    dateTime: DateTime.now(),
    indexNo: 0,
    category: dress,
    gender: kid,
    isAsset: true);

//men dress
ItemModel itemModel6 = ItemModel(
    id: DateTime.now().microsecondsSinceEpoch,
    name: "Blue Plan",
    amount: 1800.0,
    imagePath: [
      "${dressMen + "1.1.jpg"}",
      "${dressMen + "1.jpg"}",
    ],
    sizeList: [false, true, true, true],
    colorList: [],
    haveOffer: true,
    offerPer: 20,
    dateTime: DateTime.now(),
    indexNo: 0,
    category: dress,
    gender: men,
    isAsset: true);
ItemModel itemModel7 = ItemModel(
    id: DateTime.now().microsecondsSinceEpoch,
    name: "Exico Shirt",
    amount: 1200.0,
    imagePath: [
      "${dressMen + "2.1.jpg"}",
      "${dressMen + "2.jpg"}",
    ],
    sizeList: [true, true, true, true],
    colorList: [],
    haveOffer: false,
    offerPer: 40,
    dateTime: DateTime.now(),
    indexNo: 0,
    category: dress,
    gender: men,
    isAsset: true);
ItemModel itemModel8 = ItemModel(
    id: DateTime.now().microsecondsSinceEpoch,
    name: "Men Shirt",
    amount: 1000.0,
    imagePath: [
      "${dressMen + "3.1.jpg"}",
      "${dressMen + "3.jpg"}",
      "${dressMen + "3.2.jpg"}",
    ],
    sizeList: [true, true, true, true],
    colorList: [],
    haveOffer: true,
    offerPer: 20,
    dateTime: DateTime.now(),
    indexNo: 0,
    category: dress,
    gender: men,
    isAsset: true);
ItemModel itemModel9 = ItemModel(
    id: DateTime.now().microsecondsSinceEpoch,
    name: "Plane Shirt",
    amount: 1200.0,
    imagePath: [
      "${dressMen + "4.1.jpg"}",
      "${dressMen + "4.jpg"}",
    ],
    sizeList: [true, true, true, true],
    colorList: [],
    haveOffer: false,
    offerPer: 50,
    dateTime: DateTime.now(),
    indexNo: 0,
    category: dress,
    gender: men,
    isAsset: true);
ItemModel itemModel10 = ItemModel(
    id: DateTime.now().microsecondsSinceEpoch,
    name: "Men Half Curtha",
    amount: 3200.0,
    imagePath: [
      "${dressMen + "5.jpg"}",
    ],
    sizeList: [false, true, true, false],
    colorList: [],
    haveOffer: false,
    offerPer: 40,
    dateTime: DateTime.now(),
    indexNo: 0,
    category: dress,
    gender: men,
    isAsset: true);
ItemModel itemModel11 = ItemModel(
    id: DateTime.now().microsecondsSinceEpoch,
    name: "Men Curtha Coat",
    amount: 2500.0,
    imagePath: [
      "${dressMen + "6.jpg"}",
      "${dressMen + "6.1.jpg"}",
    ],
    sizeList: [false, true, true, false],
    colorList: [],
    haveOffer: true,
    offerPer: 30,
    dateTime: DateTime.now(),
    indexNo: 0,
    category: dress,
    gender: men,
    isAsset: true);

//women dress
ItemModel itemModel12 = ItemModel(
    id: DateTime.now().microsecondsSinceEpoch,
    name: "Long Top",
    amount: 900.0,
    imagePath: [
      "${dressWomen + "1.jpg"}",
      "${dressWomen + "1.1.jpg"}",
      "${dressWomen + "1.2.jpg"}",
    ],
    sizeList: [true, true, false, false],
    colorList: [],
    haveOffer: false,
    offerPer: 40,
    dateTime: DateTime.now(),
    indexNo: 0,
    category: dress,
    gender: women,
    isAsset: true);
ItemModel itemModel13 = ItemModel(
    id: DateTime.now().microsecondsSinceEpoch,
    name: "Long Top",
    amount: 1200.0,
    imagePath: [
      "${dressWomen + "2.jpg"}",
      "${dressWomen + "2.1.jpg"}",
      "${dressWomen + "2.2.jpeg"}",
    ],
    sizeList: [true, true, true, false],
    colorList: [],
    haveOffer: true,
    offerPer: 20,
    dateTime: DateTime.now(),
    indexNo: 0,
    category: dress,
    gender: kid,
    isAsset: true);
ItemModel itemModel14 = ItemModel(
    id: DateTime.now().microsecondsSinceEpoch,
    name: "Silky Long",
    amount: 1500.0,
    imagePath: [
      "${dressWomen + "3.1.jpg"}",
      "${dressWomen + "3.2.jpg"}",
    ],
    sizeList: [true, true, true, true],
    colorList: [],
    haveOffer: true,
    offerPer: 10,
    dateTime: DateTime.now(),
    indexNo: 0,
    category: dress,
    gender: women,
    isAsset: true);

//kids jersey
ItemModel itemModel15 = ItemModel(
    id: DateTime.now().microsecondsSinceEpoch,
    name: "Indian Jersey",
    amount: 500.0,
    imagePath: ["${jerseyKids + "1.jpg"}"],
    sizeList: [true, true, true, true],
    colorList: [],
    haveOffer: false,
    offerPer: 40,
    dateTime: DateTime.now(),
    indexNo: 0,
    category: jersey,
    gender: kid,
    isAsset: true);
ItemModel itemModel16 = ItemModel(
    id: DateTime.now().microsecondsSinceEpoch,
    name: "Fly Emirates",
    amount: 700.0,
    imagePath: [
      "${jerseyKids + "2.1.jpg"}",
      "${jerseyKids + "2.jpg"}",
    ],
    sizeList: [true, true, false, false],
    colorList: [],
    haveOffer: false,
    offerPer: 40,
    dateTime: DateTime.now(),
    indexNo: 0,
    category: jersey,
    gender: kid,
    isAsset: true);
ItemModel itemModel17 = ItemModel(
    id: DateTime.now().microsecondsSinceEpoch,
    name: "Jersey",
    amount: 800.0,
    imagePath: ["${jerseyKids + "3.jpg"}"],
    sizeList: [true, true, false, false],
    colorList: [],
    haveOffer: true,
    offerPer: 20,
    dateTime: DateTime.now(),
    indexNo: 0,
    category: jersey,
    gender: kid,
    isAsset: true);
ItemModel itemModel18 = ItemModel(
    id: DateTime.now().microsecondsSinceEpoch,
    name: "Jersey",
    amount: 200.0,
    imagePath: ["${jerseyKids + "4.jpg"}"],
    sizeList: [true, true, true, true],
    colorList: [],
    haveOffer: true,
    offerPer: 50,
    dateTime: DateTime.now(),
    indexNo: 0,
    category: jersey,
    gender: kid,
    isAsset: true);
ItemModel itemModel19 = ItemModel(
    id: DateTime.now().microsecondsSinceEpoch,
    name: "Jersey",
    amount: 500.0,
    imagePath: ["${jerseyKids + "5.jpg"}"],
    sizeList: [true, true, false, false],
    colorList: [],
    haveOffer: false,
    offerPer: 40,
    dateTime: DateTime.now(),
    indexNo: 0,
    category: jersey,
    gender: kid,
    isAsset: true);
ItemModel itemModel20 = ItemModel(
    id: DateTime.now().microsecondsSinceEpoch,
    name: "Jersey",
    amount: 150.0,
    imagePath: ["${jerseyKids + "7.jpg"}"],
    sizeList: [false, true, true, true],
    colorList: [],
    haveOffer: true,
    offerPer: 20,
    dateTime: DateTime.now(),
    indexNo: 0,
    category: jersey,
    gender: kid,
    isAsset: true);

//men jersey
ItemModel itemModel21 = ItemModel(
    id: DateTime.now().microsecondsSinceEpoch,
    name: "RCB Jersey",
    amount: 1200.0,
    imagePath: [
      "${jerseyMen + "1.jpg"}",
      "${jerseyMen + "1.1.jpg"}",
      "${jerseyMen + "1.2.jpg"}",
    ],
    sizeList: [true, true, true, true],
    colorList: [],
    haveOffer: false,
    offerPer: 40,
    dateTime: DateTime.now(),
    indexNo: 0,
    category: jersey,
    gender: men,
    isAsset: true);
ItemModel itemModel22 = ItemModel(
    id: DateTime.now().microsecondsSinceEpoch,
    name: "Jersey",
    amount: 400.0,
    imagePath: ["${jerseyMen + "2.jpg"}"],
    sizeList: [true, true, true, true],
    colorList: [],
    haveOffer: true,
    offerPer: 20,
    dateTime: DateTime.now(),
    indexNo: 0,
    category: jersey,
    gender: men,
    isAsset: true);
ItemModel itemModel23 = ItemModel(
    id: DateTime.now().microsecondsSinceEpoch,
    name: "Blue White",
    amount: 700.0,
    imagePath: [
      "${jerseyMen + "3.1.jpg"}",
      "${jerseyMen + "3.jpg"}",
    ],
    sizeList: [true, true, true, true],
    colorList: [],
    haveOffer: false,
    offerPer: 50,
    dateTime: DateTime.now(),
    indexNo: 0,
    category: jersey,
    gender: men,
    isAsset: true);
ItemModel itemModel24 = ItemModel(
    id: DateTime.now().microsecondsSinceEpoch,
    name: "Color Jersey",
    amount: 700.0,
    imagePath: ["${jerseyMen + "4.jpg"}"],
    sizeList: [false, true, true, false],
    colorList: [],
    haveOffer: false,
    offerPer: 40,
    dateTime: DateTime.now(),
    indexNo: 0,
    category: jersey,
    gender: men,
    isAsset: true);
ItemModel itemModel25 = ItemModel(
    id: DateTime.now().microsecondsSinceEpoch,
    name: "Jersey",
    amount: 700.0,
    imagePath: ["${jerseyMen + "5.jpg"}", "${jerseyMen + "5.1.jpg"}"],
    sizeList: [false, true, true, false],
    colorList: [],
    haveOffer: true,
    offerPer: 30,
    dateTime: DateTime.now(),
    indexNo: 0,
    category: jersey,
    gender: men,
    isAsset: true);
ItemModel itemModel26 = ItemModel(
    id: DateTime.now().microsecondsSinceEpoch,
    name: "Fire Jersey",
    amount: 1300.0,
    imagePath: ["${jerseyMen + "6.jpg"}"],
    sizeList: [true, true, false, false],
    colorList: [],
    haveOffer: false,
    offerPer: 40,
    dateTime: DateTime.now(),
    indexNo: 0,
    category: jersey,
    gender: men,
    isAsset: true);

//women jersey
ItemModel itemModel27 = ItemModel(
    id: DateTime.now().microsecondsSinceEpoch,
    name: "RCB Jersey",
    amount: 500.0,
    imagePath: ["${jerseyWomen + "1.webp"}"],
    sizeList: [true, true, true, false],
    colorList: [],
    haveOffer: true,
    offerPer: 20,
    dateTime: DateTime.now(),
    indexNo: 0,
    category: jersey,
    gender: women,
    isAsset: true);
ItemModel itemModel28 = ItemModel(
    id: DateTime.now().microsecondsSinceEpoch,
    name: "Jeep Jersey",
    amount: 1000.0,
    imagePath: [
      "${jerseyWomen + "2.jpg"}",
      "${jerseyWomen + "2.1.jpg"}",
      "${jerseyWomen + "2.2.jpg"}",
    ],
    sizeList: [true, true, true, true],
    colorList: [],
    haveOffer: true,
    offerPer: 10,
    dateTime: DateTime.now(),
    indexNo: 0,
    category: jersey,
    gender: women,
    isAsset: true);
ItemModel itemModel29 = ItemModel(
    id: DateTime.now().microsecondsSinceEpoch,
    name: "Indian Jersey",
    amount: 400.0,
    imagePath: [
      "${jerseyWomen + "3.jpg"}",
      "${jerseyWomen + "3.1.jpg"}",
      "${jerseyWomen + "3.2.jpg"}"
    ],
    sizeList: [true, true, true, false],
    colorList: [],
    haveOffer: true,
    offerPer: 20,
    dateTime: DateTime.now(),
    indexNo: 0,
    category: jersey,
    gender: women,
    isAsset: true);
ItemModel itemModel30 = ItemModel(
    id: DateTime.now().microsecondsSinceEpoch,
    name: "Track Jersey",
    amount: 2000.0,
    imagePath: ["${jerseyWomen + "4.jpg"}"],
    sizeList: [true, true, true, true],
    colorList: [],
    haveOffer: true,
    offerPer: 10,
    dateTime: DateTime.now(),
    indexNo: 0,
    category: jersey,
    gender: women,
    isAsset: true);
ItemModel itemModel31 = ItemModel(
    id: DateTime.now().microsecondsSinceEpoch,
    name: "Track Jersey",
    amount: 500.0,
    imagePath: ["${jerseyWomen + "5.jpg"}", "${jerseyWomen + "5.1.jpg"}"],
    sizeList: [true, true, true, false],
    colorList: [],
    haveOffer: true,
    offerPer: 20,
    dateTime: DateTime.now(),
    indexNo: 0,
    category: jersey,
    gender: women,
    isAsset: true);
ItemModel itemModel32 = ItemModel(
    id: DateTime.now().microsecondsSinceEpoch,
    name: "Jersey",
    amount: 7000.0,
    imagePath: ["${jerseyWomen + "6.jpg"}"],
    sizeList: [true, true, true, true],
    colorList: [],
    haveOffer: true,
    offerPer: 10,
    dateTime: DateTime.now(),
    indexNo: 0,
    category: jersey,
    gender: women,
    isAsset: true);

//kids pants
ItemModel itemModel33 = ItemModel(
    id: DateTime.now().microsecondsSinceEpoch,
    name: "Yellow Pant",
    amount: 800.0,
    imagePath: ["${pantsKids + "1.png"}", "${pantsKids + "1.1.jpeg"}"],
    sizeList: [true, true, false, false],
    colorList: [],
    haveOffer: true,
    offerPer: 20,
    dateTime: DateTime.now(),
    indexNo: 0,
    category: pants,
    gender: kid,
    isAsset: true);
ItemModel itemModel34 = ItemModel(
    id: DateTime.now().microsecondsSinceEpoch,
    name: "Trouser",
    amount: 500.0,
    imagePath: [
      "${pantsKids + "2.jpg"}",
      "${pantsKids + "2.1.jpg"}",
      "${pantsKids + "2.2.jpg"}"
    ],
    sizeList: [true, true, false, false],
    colorList: [],
    haveOffer: true,
    offerPer: 50,
    dateTime: DateTime.now(),
    indexNo: 0,
    category: pants,
    gender: kid,
    isAsset: true);
ItemModel itemModel35 = ItemModel(
    id: DateTime.now().microsecondsSinceEpoch,
    name: "Full Pant",
    amount: 1500.0,
    imagePath: [
      "${pantsKids + "3.1.jpg"}",
      "${pantsKids + "3.jpeg"}",
      "${pantsKids + "3.2.jpg"}"
    ],
    sizeList: [true, true, false, false],
    colorList: [],
    haveOffer: false,
    offerPer: 40,
    dateTime: DateTime.now(),
    indexNo: 0,
    category: pants,
    gender: kid,
    isAsset: true);
ItemModel itemModel36 = ItemModel(
    id: DateTime.now().microsecondsSinceEpoch,
    name: "Red Pants",
    amount: 700.0,
    imagePath: ["${pantsKids + "4.jpg"}"],
    sizeList: [false, true, true, true],
    colorList: [],
    haveOffer: true,
    offerPer: 20,
    dateTime: DateTime.now(),
    indexNo: 0,
    category: pants,
    gender: kid,
    isAsset: true);
ItemModel itemModel37 = ItemModel(
    id: DateTime.now().microsecondsSinceEpoch,
    name: "Track Pant",
    amount: 1200.0,
    imagePath: [
      "${pantsKids + "5.1.jpg"}",
      "${pantsKids + "5.jpg"}",
      "${pantsKids + "5.2.webp"}",
    ],
    sizeList: [true, true, true, true],
    colorList: [],
    haveOffer: false,
    offerPer: 40,
    dateTime: DateTime.now(),
    indexNo: 0,
    category: pants,
    gender: kid,
    isAsset: true);

//men pants
ItemModel itemModel38 = ItemModel(
    id: DateTime.now().microsecondsSinceEpoch,
    name: "Men Pant",
    amount: 1000.0,
    imagePath: [
      "${pantsMen + "1.1.jpg"}",
      "${pantsMen + "1.jpg"}",
      "${pantsMen + "1.2.jpg"}",
    ],
    sizeList: [true, true, true, true],
    colorList: [],
    haveOffer: true,
    offerPer: 20,
    dateTime: DateTime.now(),
    indexNo: 0,
    category: pants,
    gender: men,
    isAsset: true);
ItemModel itemModel39 = ItemModel(
    id: DateTime.now().microsecondsSinceEpoch,
    name: "Plane Pant",
    amount: 1200.0,
    imagePath: [
      "${pantsMen + "2.1.jpg"}",
      "${pantsMen + "2.jpg"}",
    ],
    sizeList: [true, true, true, true],
    colorList: [],
    haveOffer: false,
    offerPer: 50,
    dateTime: DateTime.now(),
    indexNo: 0,
    category: pants,
    gender: men,
    isAsset: true);
ItemModel itemModel40 = ItemModel(
    id: DateTime.now().microsecondsSinceEpoch,
    name: "Pants",
    amount: 3200.0,
    imagePath: [
      "${pantsMen + "3.jpg"}",
      "${pantsMen + "3.1.jpg"}",
      "${pantsMen + "3.2.jpg"}",
    ],
    sizeList: [false, true, true, false],
    colorList: [],
    haveOffer: false,
    offerPer: 40,
    dateTime: DateTime.now(),
    indexNo: 0,
    category: pants,
    gender: men,
    isAsset: true);
ItemModel itemModel41 = ItemModel(
    id: DateTime.now().microsecondsSinceEpoch,
    name: "Pants",
    amount: 2000.0,
    imagePath: [
      "${pantsMen + "4.jpg"}",
      "${pantsMen + "4.1.jpg"}",
    ],
    sizeList: [false, true, true, false],
    colorList: [],
    haveOffer: true,
    offerPer: 30,
    dateTime: DateTime.now(),
    indexNo: 0,
    category: pants,
    gender: men,
    isAsset: true);
ItemModel itemModel42 = ItemModel(
    id: DateTime.now().microsecondsSinceEpoch,
    name: "Pants",
    amount: 1000.0,
    imagePath: ["${pantsMen + "5.jpg"}"],
    sizeList: [false, true, true, false],
    colorList: [],
    haveOffer: true,
    offerPer: 30,
    dateTime: DateTime.now(),
    indexNo: 0,
    category: pants,
    gender: men,
    isAsset: true);

//women pants
ItemModel itemModel43 = ItemModel(
    id: DateTime.now().microsecondsSinceEpoch,
    name: "Long Pant",
    amount: 1200.0,
    imagePath: ["${pantsWomen + "1.jpeg"}", "${pantsWomen + "1.1.jpg"}"],
    sizeList: [true, true, true, false],
    colorList: [],
    haveOffer: true,
    offerPer: 20,
    dateTime: DateTime.now(),
    indexNo: 0,
    category: pants,
    gender: women,
    isAsset: true);
ItemModel itemModel44 = ItemModel(
    id: DateTime.now().microsecondsSinceEpoch,
    name: "Ladies Pant",
    amount: 800.0,
    imagePath: [
      "${pantsWomen + "2.webp"}",
      "${pantsWomen + "2.1.webp"}",
      "${pantsWomen + "2.2.jpg"}"
    ],
    sizeList: [true, true, true, false],
    colorList: [],
    haveOffer: true,
    offerPer: 20,
    dateTime: DateTime.now(),
    indexNo: 0,
    category: pants,
    gender: women,
    isAsset: true);
ItemModel itemModel45 = ItemModel(
    id: DateTime.now().microsecondsSinceEpoch,
    name: "Pant",
    amount: 1200.0,
    imagePath: [
      "${pantsWomen + "3.webp"}",
      "${pantsWomen + "3.1.webp"}",
      "${pantsWomen + "3.2.jpg"}",
    ],
    sizeList: [true, true, true, false],
    colorList: [],
    haveOffer: true,
    offerPer: 20,
    dateTime: DateTime.now(),
    indexNo: 0,
    category: pants,
    gender: women,
    isAsset: true);
ItemModel itemModel46 = ItemModel(
    id: DateTime.now().microsecondsSinceEpoch,
    name: "Print Pant",
    amount: 1200.0,
    imagePath: [
      "${pantsWomen + "4.jpg"}",
      "${pantsWomen + "4.1.jpg"}",
      "${pantsWomen + "4.2.jpg"}",
    ],
    sizeList: [true, true, true, false],
    colorList: [],
    haveOffer: true,
    offerPer: 20,
    dateTime: DateTime.now(),
    indexNo: 0,
    category: pants,
    gender: women,
    isAsset: true);

//kids coats
ItemModel itemModel47 = ItemModel(
    id: DateTime.now().microsecondsSinceEpoch,
    name: "Pink Coat",
    amount: 1800.0,
    imagePath: [
      "${coatsKids + "1.jpg"}",
      "${coatsKids + "1.1.jpg"}",
    ],
    sizeList: [true, true, false, false],
    colorList: [],
    haveOffer: true,
    offerPer: 20,
    dateTime: DateTime.now(),
    indexNo: 0,
    category: coats,
    gender: kid,
    isAsset: true);
ItemModel itemModel48 = ItemModel(
    id: DateTime.now().microsecondsSinceEpoch,
    name: "Coat",
    amount: 1100.0,
    imagePath: ["${coatsKids + "2.jpg"}"],
    sizeList: [true, true, false, false],
    colorList: [],
    haveOffer: true,
    offerPer: 20,
    dateTime: DateTime.now(),
    indexNo: 0,
    category: coats,
    gender: kid,
    isAsset: true);
ItemModel itemModel49 = ItemModel(
    id: DateTime.now().microsecondsSinceEpoch,
    name: "Coat",
    amount: 900.0,
    imagePath: ["${coatsKids + "3.jpg"}"],
    sizeList: [true, true, false, false],
    colorList: [],
    haveOffer: true,
    offerPer: 20,
    dateTime: DateTime.now(),
    indexNo: 0,
    category: coats,
    gender: kid,
    isAsset: true);
ItemModel itemModel50 = ItemModel(
    id: DateTime.now().microsecondsSinceEpoch,
    name: "Coat",
    amount: 1400.0,
    imagePath: [
      "${coatsKids + "4.jpeg"}",
      "${coatsKids + "4.1.jpg"}",
    ],
    sizeList: [true, true, false, false],
    colorList: [],
    haveOffer: true,
    offerPer: 20,
    dateTime: DateTime.now(),
    indexNo: 0,
    category: coats,
    gender: kid,
    isAsset: true);
ItemModel itemModel51 = ItemModel(
    id: DateTime.now().microsecondsSinceEpoch,
    name: "Coat",
    amount: 2200.0,
    imagePath: ["${coatsKids + "5.jpg"}"],
    sizeList: [true, true, false, false],
    colorList: [],
    haveOffer: true,
    offerPer: 20,
    dateTime: DateTime.now(),
    indexNo: 0,
    category: coats,
    gender: kid,
    isAsset: true);
ItemModel itemModel52 = ItemModel(
    id: DateTime.now().microsecondsSinceEpoch,
    name: "oat",
    amount: 1800.0,
    imagePath: ["${coatsKids + "6.jpg"}"],
    sizeList: [true, true, false, false],
    colorList: [],
    haveOffer: true,
    offerPer: 20,
    dateTime: DateTime.now(),
    indexNo: 0,
    category: coats,
    gender: kid,
    isAsset: true);

//men coats
ItemModel itemModel53 = ItemModel(
    id: DateTime.now().microsecondsSinceEpoch,
    name: "Horse Coat",
    amount: 1500.0,
    imagePath: [
      "${coatsMen + "1.webp"}",
      "${coatsMen + "1.1.jpg"}",
      "${coatsMen + "1.2.jpg"}",
    ],
    sizeList: [true, true, true, true],
    colorList: [],
    haveOffer: false,
    offerPer: 50,
    dateTime: DateTime.now(),
    indexNo: 0,
    category: coats,
    gender: men,
    isAsset: true);
ItemModel itemModel54 = ItemModel(
    id: DateTime.now().microsecondsSinceEpoch,
    name: "Black Coat",
    amount: 2500.0,
    imagePath: [
      "${coatsMen + "2.jpg"}",
      "${coatsMen + "2.1.jpg"}",
      "${coatsMen + "2.2.jpg"}",
    ],
    sizeList: [true, true, true, true],
    colorList: [],
    haveOffer: true,
    offerPer: 50,
    dateTime: DateTime.now(),
    indexNo: 0,
    category: coats,
    gender: men,
    isAsset: true);
ItemModel itemModel55 = ItemModel(
    id: DateTime.now().microsecondsSinceEpoch,
    name: "Half Black Coat",
    amount: 7500.0,
    imagePath: [
      "${coatsMen + "3.jpg"}",
      "${coatsMen + "3.1.jpg"}",
      "${coatsMen + "3.2.jpg"}",
    ],
    sizeList: [true, true, true, true],
    colorList: [],
    haveOffer: true,
    offerPer: 50,
    dateTime: DateTime.now(),
    indexNo: 0,
    category: coats,
    gender: men,
    isAsset: true);
ItemModel itemModel56 = ItemModel(
    id: DateTime.now().microsecondsSinceEpoch,
    name: "Men Coat",
    amount: 3500.0,
    imagePath: [
      "${coatsMen + "4.jpg"}",
    ],
    sizeList: [true, true, true, true],
    colorList: [],
    haveOffer: true,
    offerPer: 50,
    dateTime: DateTime.now(),
    indexNo: 0,
    category: coats,
    gender: men,
    isAsset: true);
ItemModel itemModel57 = ItemModel(
    id: DateTime.now().microsecondsSinceEpoch,
    name: "Winter Coat",
    amount: 10500.0,
    imagePath: [
      "${coatsMen + "6.jpg"}",
    ],
    sizeList: [true, true, true, true],
    colorList: [],
    haveOffer: true,
    offerPer: 50,
    dateTime: DateTime.now(),
    indexNo: 0,
    category: coats,
    gender: men,
    isAsset: true);

//women coats
ItemModel itemModel58 = ItemModel(
    id: DateTime.now().microsecondsSinceEpoch,
    name: "Women Coat",
    amount: 4400.0,
    imagePath: [
      "${coatsWomen + "1.jpg"}",
      "${coatsWomen + "1.2.jpg"}",
      "${coatsWomen + "1.3.jpg"}",
    ],
    sizeList: [true, true, true, false],
    colorList: [],
    haveOffer: true,
    offerPer: 20,
    dateTime: DateTime.now(),
    indexNo: 0,
    category: coats,
    gender: women,
    isAsset: true);
ItemModel itemModel59 = ItemModel(
    id: DateTime.now().microsecondsSinceEpoch,
    name: "Winter Coat",
    amount: 9400.0,
    imagePath: [
      "${coatsWomen + "2.jpg"}",
    ],
    sizeList: [true, true, true, false],
    colorList: [],
    haveOffer: true,
    offerPer: 30,
    dateTime: DateTime.now(),
    indexNo: 0,
    category: coats,
    gender: women,
    isAsset: true);
ItemModel itemModel60 = ItemModel(
    id: DateTime.now().microsecondsSinceEpoch,
    name: "Half Blue Coat",
    amount: 8500.0,
    imagePath: [
      "${coatsWomen + "3.jpg"}",
      "${coatsWomen + "3.1.jpg"}",
      "${coatsWomen + "3.2.jpg"}",
    ],
    sizeList: [true, true, true, false],
    colorList: [],
    haveOffer: false,
    offerPer: 20,
    dateTime: DateTime.now(),
    indexNo: 0,
    category: coats,
    gender: women,
    isAsset: true);
ItemModel itemModel61 = ItemModel(
    id: DateTime.now().microsecondsSinceEpoch,
    name: "Grey Top Coat",
    amount: 4400.0,
    imagePath: [
      "${coatsWomen + "5.png"}",
      "${coatsWomen + "5.1.png"}",
    ],
    sizeList: [true, true, true, false],
    colorList: [],
    haveOffer: false,
    offerPer: 20,
    dateTime: DateTime.now(),
    indexNo: 0,
    category: coats,
    gender: women,
    isAsset: true);

List<ItemModel> dummyItems = [
  itemModel1,
  itemModel2,
  itemModel3,
  itemModel4,
  itemModel5,
  itemModel6,
  itemModel7,
  itemModel8,
  itemModel9,
  itemModel10,
  itemModel11,
  itemModel12,
  itemModel13,
  itemModel14,
  itemModel15,
  itemModel16,
  itemModel17,
  itemModel18,
  itemModel19,
  itemModel20,
  itemModel21,
  itemModel22,
  itemModel23,
  itemModel24,
  itemModel25,
  itemModel26,
  itemModel27,
  itemModel28,
  itemModel29,
  itemModel30,
  itemModel31,
  itemModel32,
  itemModel33,
  itemModel34,
  itemModel35,
  itemModel36,
  itemModel37,
  itemModel38,
  itemModel39,
  itemModel40,
  itemModel41,
  itemModel42,
  itemModel43,
  itemModel44,
  itemModel45,
  itemModel46,
  itemModel47,
  itemModel48,
  itemModel49,
  itemModel50,
  itemModel51,
  itemModel52,
  itemModel53,
  itemModel54,
  itemModel55,
  itemModel56,
  itemModel57,
  itemModel58,
  itemModel59,
  itemModel60,
  itemModel61,
];
